import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execSync } from 'node:child_process';
import { init } from '../lib/init.js';

let DIR;
const settings = () => JSON.parse(fs.readFileSync(path.join(DIR, '.claude', 'settings.json'), 'utf8'));

beforeEach(() => { DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'reflex-init-')); });
afterEach(() => { fs.rmSync(DIR, { recursive: true, force: true }); });

describe('init', () => {
  it('wires hooks in the shape Claude Code reads', () => {
    init(DIR);
    const s = settings();
    for (const ev of ['UserPromptSubmit', 'PostToolUse', 'PostToolUseFailure', 'Stop']) {
      expect(s.hooks[ev]).toEqual([
        { hooks: [{ type: 'command', command: `node "$CLAUDE_PROJECT_DIR/.claude/hooks/reflex.mjs" ${ev}` }] },
      ]);
    }
  });

  it('is idempotent and preserves unrelated hooks', () => {
    fs.mkdirSync(path.join(DIR, '.claude'), { recursive: true });
    fs.writeFileSync(path.join(DIR, '.claude', 'settings.json'), JSON.stringify({
      permissions: { allow: ['Bash(ls)'] },
      hooks: { Stop: [{ hooks: [{ type: 'command', command: 'say done' }] }] },
    }));

    init(DIR);
    init(DIR);

    const s = settings();
    expect(s.permissions).toEqual({ allow: ['Bash(ls)'] });
    expect(s.hooks.Stop).toHaveLength(2);
    expect(s.hooks.Stop[0].hooks[0].command).toBe('say done');
    expect(s.hooks.UserPromptSubmit).toHaveLength(1);
  });

  it('gitignores every runtime artifact except the committed allowlist', () => {
    // A pre-existing whole-dir ignore would silently defeat the allowlist.
    fs.writeFileSync(path.join(DIR, '.gitignore'), 'node_modules/\n.reflex/\n.reflex/traces/\n');
    execSync('git init -q', { cwd: DIR });

    init(DIR);
    init(DIR);

    const gitignore = fs.readFileSync(path.join(DIR, '.gitignore'), 'utf8');
    expect(gitignore).toContain('node_modules/');
    expect(gitignore.match(/\.reflex\/\*/g)).toHaveLength(1);

    fs.mkdirSync(path.join(DIR, '.reflex', 'traces'), { recursive: true });
    fs.writeFileSync(path.join(DIR, '.reflex', 'traces', 't.jsonl'), '');
    fs.writeFileSync(path.join(DIR, '.reflex', 'worker.log'), '');
    fs.writeFileSync(path.join(DIR, '.reflex', 'pending.jsonl'), '');
    fs.writeFileSync(path.join(DIR, '.reflex', 'processing.jsonl'), '');
    const ignored = (file) =>
      execSync(`git check-ignore -q "${file}" && echo yes || echo no`, { cwd: DIR, shell: '/bin/sh' })
        .toString().trim() === 'yes';

    for (const file of ['config.json', 'procedures.jsonl', 'runs.jsonl', 'runtime.js']) {
      expect(ignored(`.reflex/${file}`), file).toBe(false);
    }
    expect(ignored('.reflex/traces/t.jsonl')).toBe(true);
    expect(ignored('.reflex/worker.log')).toBe(true);
    expect(ignored('.reflex/pending.jsonl')).toBe(true);
    expect(ignored('.reflex/processing.jsonl')).toBe(true);
  });

  it('installs one runtime file and a thin shim, and drops a leftover engine dir', () => {
    const engine = path.join(DIR, '.reflex', 'engine', 'harnesses');
    fs.mkdirSync(engine, { recursive: true });
    fs.writeFileSync(path.join(engine, 'claude.js'), 'old');

    init(DIR);

    expect(fs.existsSync(path.join(DIR, '.reflex', 'engine'))).toBe(false);
    const version = JSON.parse(fs.readFileSync(new URL('../package.json', import.meta.url), 'utf8')).version;
    const runtime = fs.readFileSync(path.join(DIR, '.reflex', 'runtime.js'), 'utf8');
    expect(runtime.startsWith(`// Generated by agent-procedures@${version}. Do not edit.\n`)).toBe(true);
    expect(runtime).toContain('To upgrade: npx agent-procedures init');
    expect(runtime).not.toMatch(/from ["']\.\/groomer\.js["']/);
    const shim = fs.readFileSync(path.join(DIR, '.claude', 'hooks', 'reflex.mjs'), 'utf8');
    expect(shim).toContain('from "../../.reflex/runtime.js"');
    expect(shim).toContain('run("claude")');
    expect(JSON.parse(fs.readFileSync(path.join(DIR, '.reflex', 'config.json'), 'utf8')).harness).toBe('claude');
  });

  it('rejects an unknown harness', () => {
    expect(() => init(DIR, { harness: 'nope' })).toThrow(/Unknown harness "nope"/);
  });

  it('shim runs end to end the way Claude Code would call it', () => {
    init(DIR);
    const hook = (event, payload) =>
      execSync(`node .claude/hooks/reflex.mjs ${event}`, { cwd: DIR, input: JSON.stringify(payload), encoding: 'utf8' });
    const ids = { session_id: 's1', prompt_id: 'p1' };

    expect(hook('UserPromptSubmit', { ...ids, hook_event_name: 'UserPromptSubmit', prompt: 'lint and fix' }).trim()).toBe('{}');
    hook('PostToolUse', { ...ids, hook_event_name: 'PostToolUse', tool_name: 'Bash', tool_input: { command: 'npm run lint -- --fix' } });
    hook('Stop', { ...ids, hook_event_name: 'Stop', stop_hook_active: false });

    const [node] = fs.readFileSync(path.join(DIR, '.reflex', 'pending.jsonl'), 'utf8').trim().split('\n').map(JSON.parse);
    expect(node.steps).toEqual([{ t: 'Bash', target: 'npm run lint -- --fix' }]);
    expect(fs.readFileSync(path.join(DIR, '.reflex', 'procedures.jsonl'), 'utf8').trim()).toBe('');

    const out = JSON.parse(hook('UserPromptSubmit', { session_id: 's2', prompt_id: 'p2', hook_event_name: 'UserPromptSubmit', prompt: 'please lint and fix it' }));
    expect(out.hookSpecificOutput.hookEventName).toBe('UserPromptSubmit');
    expect(out.hookSpecificOutput.additionalContext).toContain('npm run lint -- --fix');
    expect(out.systemMessage).toMatch(/^Reflex recalled: "/);
  });
});
