import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_HARNESS, getHarness } from "./harnesses/index.js";

const LIB_DIR = path.dirname(fileURLToPath(import.meta.url));

const DEFAULT_CONFIG = {
  version: 1,
  harness: "claude",
  minConfidence: 0.7,
  store: {
    procedures: "procedures.jsonl",
    runs: "runs.jsonl",
  },
};

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    return "created";
  }
  return "exists";
}

function writeIfMissing(filePath, contents) {
  if (fs.existsSync(filePath)) {
    return "skipped";
  }
  fs.writeFileSync(filePath, contents, "utf8");
  return "created";
}

function writeAlways(filePath, contents) {
  fs.writeFileSync(filePath, contents, "utf8");
  return "updated";
}

function ensureGitignore(cwd) {
  const gitignorePath = path.join(cwd, ".gitignore");
  const entry = ".reflex/traces/";

  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, `${entry}\n`, "utf8");
    return "created";
  }

  const current = fs.readFileSync(gitignorePath, "utf8");
  const lines = current.split(/\r?\n/);
  const alreadyIgnored = lines.some(
    (line) =>
      line.trim() === ".reflex/traces/" || line.trim() === ".reflex/traces",
  );

  if (alreadyIgnored) {
    return "exists";
  }

  const suffix = current.endsWith("\n") || current.length === 0 ? "" : "\n";
  fs.writeFileSync(gitignorePath, `${current}${suffix}${entry}\n`, "utf8");
  return "updated";
}

// Runtime that gets copied into <repo>/.reflex/engine/. npx doesn't leave the
// package behind, so the repo has to carry the engine. Harness-neutral location
// so several harnesses in one repo share a single copy.
const ENGINE_FILES = [
  "main.js",
  "engine.js",
  "store.js",
  "groomer.js",
  "providers.js",
  "harnesses/index.js",
  "harnesses/claude.js",
];

function installEngine(reflexDir) {
  const engineDir = path.join(reflexDir, "engine");
  for (const f of ENGINE_FILES) {
    const dest = path.join(engineDir, f);
    ensureDir(path.dirname(dest));
    fs.copyFileSync(path.join(LIB_DIR, f), dest);
  }
  return "updated";
}

// A few lines that point the harness's hook at the shared engine.
function writeShim(cwd, harness) {
  const hookPath = path.join(cwd, harness.hookFile);
  const enginePath = path.join(cwd, ".reflex", "engine", "main.js");
  let rel = path.relative(path.dirname(hookPath), enginePath).split(path.sep).join("/");
  if (!rel.startsWith(".")) rel = "./" + rel;

  ensureDir(path.dirname(hookPath));
  writeAlways(
    hookPath,
    `#!/usr/bin/env node
// Generated by agent-procedures init. Re-run init to refresh; do not edit.
import { run } from "${rel}";
await run(${JSON.stringify(harness.id)});
`,
  );
  fs.chmodSync(hookPath, 0o755);
}

export function init(cwd = process.cwd(), { harness: harnessId = DEFAULT_HARNESS } = {}) {
  const harness = getHarness(harnessId);
  const reflexDir = path.join(cwd, ".reflex");
  const tracesDir = path.join(reflexDir, "traces");

  ensureDir(reflexDir);
  ensureDir(tracesDir);

  const results = {
    dir: "exists",
    config: writeIfMissing(
      path.join(reflexDir, "config.json"),
      `${JSON.stringify({ ...DEFAULT_CONFIG, harness: harness.id }, null, 2)}\n`,
    ),
    procedures: writeIfMissing(path.join(reflexDir, "procedures.jsonl"), ""),
    runs: writeIfMissing(path.join(reflexDir, "runs.jsonl"), ""),
    gitignore: ensureGitignore(cwd),
    engine: installEngine(reflexDir),
  };

  writeShim(cwd, harness);
  harness.register(cwd);
  results.hooks = "updated";

  return results;
}
