import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_HARNESS, getHarness } from "./harnesses/index.js";
import { migrateLegacyPending } from "./store.js";

const LIB_DIR = path.dirname(fileURLToPath(import.meta.url));

const DEFAULT_CONFIG = {
  version: 1,
  harness: "claude",
  minConfidence: 0.7,
  store: {
    procedures: "procedures.jsonl",
    runs: "runs.jsonl",
  },
};

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    return "created";
  }
  return "exists";
}

function writeIfMissing(filePath, contents) {
  if (fs.existsSync(filePath)) {
    return "skipped";
  }
  fs.writeFileSync(filePath, contents, "utf8");
  return "created";
}

function writeAlways(filePath, contents) {
  fs.writeFileSync(filePath, contents, "utf8");
  return "updated";
}

function ensureGitignore(cwd) {
  const gitignorePath = path.join(cwd, ".gitignore");
  const block = [
    "# Reflex: ignore runtime state; commit only the shared allowlist",
    ".reflex/*",
    "!.reflex/config.json",
    "!.reflex/procedures.jsonl",
    "!.reflex/runs.jsonl",
    "!.reflex/runtime.js",
  ];
  // A whole-dir ignore (".reflex/") would defeat the allowlist: git cannot
  // re-include a file whose parent directory is excluded.
  const managed = new Set([
    ...block,
    ".reflex",
    ".reflex/",
    ".reflex/traces",
    ".reflex/traces/",
  ]);
  const existed = fs.existsSync(gitignorePath);
  const current = existed ? fs.readFileSync(gitignorePath, "utf8") : "";
  const kept = current
    .split(/\r?\n/)
    .filter((line) => !managed.has(line.trim()));
  while (kept.length > 0 && kept.at(-1) === "") kept.pop();
  const next = [...kept, ...(kept.length > 0 ? [""] : []), ...block].join("\n") + "\n";

  if (next === current) return "exists";
  fs.writeFileSync(gitignorePath, next, "utf8");
  return existed ? "updated" : "created";
}

// One bundled file, built by `npm run build` into dist/runtime.js.
// npx doesn't leave the package behind, so the repo carries this artifact.
const RUNTIME_SRC = path.join(LIB_DIR, "..", "dist", "runtime.js");

function installRuntime(reflexDir) {
  if (!fs.existsSync(RUNTIME_SRC)) {
    throw new Error("Missing dist/runtime.js. Run `npm run build` in the agent-procedures repo first.");
  }
  fs.copyFileSync(RUNTIME_SRC, path.join(reflexDir, "runtime.js"));
  const engineDir = path.join(reflexDir, "engine");
  if (fs.existsSync(engineDir)) fs.rmSync(engineDir, { recursive: true, force: true });
  return "updated";
}

// A few lines that point the harness's hook at the shared engine.
function writeShim(cwd, harness) {
  const hookPath = path.join(cwd, harness.hookFile);
  const enginePath = path.join(cwd, ".reflex", "runtime.js");
  let rel = path.relative(path.dirname(hookPath), enginePath).split(path.sep).join("/");
  if (!rel.startsWith(".")) rel = "./" + rel;

  ensureDir(path.dirname(hookPath));
  writeAlways(
    hookPath,
    `#!/usr/bin/env node
// Generated by agent-procedures init. Re-run init to refresh; do not edit.
import { run } from "${rel}";
await run(${JSON.stringify(harness.id)});
`,
  );
  fs.chmodSync(hookPath, 0o755);
}

export function init(cwd = process.cwd(), { harness: harnessId = DEFAULT_HARNESS } = {}) {
  const harness = getHarness(harnessId);
  const reflexDir = path.join(cwd, ".reflex");
  const tracesDir = path.join(reflexDir, "traces");

  ensureDir(reflexDir);
  ensureDir(tracesDir);

  const results = {
    dir: "exists",
    config: writeIfMissing(
      path.join(reflexDir, "config.json"),
      `${JSON.stringify({ ...DEFAULT_CONFIG, harness: harness.id }, null, 2)}\n`,
    ),
    procedures: writeIfMissing(path.join(reflexDir, "procedures.jsonl"), ""),
    runs: writeIfMissing(path.join(reflexDir, "runs.jsonl"), ""),
    gitignore: ensureGitignore(cwd),
    runtime: installRuntime(reflexDir),
  };

  writeShim(cwd, harness);
  harness.register(cwd);
  results.hooks = "updated";
  results.migrate = migrateLegacyPending(reflexDir).moved > 0 ? "moved" : "noop";

  return results;
}
