import esbuild from "esbuild";
import fs from "node:fs";

const pkg = JSON.parse(fs.readFileSync(new URL("../package.json", import.meta.url), "utf8"));

await esbuild.build({
  entryPoints: ["lib/main.js"],
  outfile: "dist/runtime.js",
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node18",
  minify: false,
  banner: {
    js: [
      `// Generated by agent-procedures@${pkg.version}. Do not edit.`,
      "// To upgrade: npx agent-procedures init",
    ].join("\n"),
  },
});
